### ISSUE TITLE
Doesn't support LyCORIS 

### ISSUE THREAD

**Issue by NoxiousPluK** [civitai/comfy-nodes#2]
From what I understand ([1](https://github.com/comfyanonymous/ComfyUI#features), [2](https://www.reddit.com/r/comfyui/comments/12ugkli/is_there_a_plan_to_support_lycorisloconloras/jh7lq5w/)), LyCORIS should work out-of-the-box as a LoRA in ComfyUI.

But when trying to use [119446](https://civitai.com/models/119446/holloai-xl-v10), I get `Exception: [CivitAI] Error: The model you requested is not a valid LORA. Aborting!`

**Comment by WASasquatch** [comment]
You are absolutely correct. And that is my bad. Because "LoCon" wasn't in the REST API reference for CivitAI I mistakenly assumed LyCORIS were just under the LORA model type on the API. I just confirmed the model type returned by the API is "*LoCon*" and not "LORA". 

I have patched this for an upcoming update. Thank you for bringing it to our attention.

**Comment by WASasquatch** [comment]
This should be patched in https://github.com/civitai/comfy-nodes/commit/d556af6e3663329868bee416ed517c945f13b7f0#diff-3b06fd4f05bd2d561da1675c2e2df79f84573749ccb340d4e024bc9d886fa820R140

**Comment by NoxiousPluK** [comment]
Amazing, thank you! Can confirm this now works:

[CivitAI] Downloading `SDXL_holloAI_v1.0.safetensors` from `https://civitai.com/api/download/models/129771`
7.46MB [00:08, 921kB/s]
[CivitAI] Loading LoCon: SDXL_holloAI_v1.0.safetensors (https://civitai.com/models/119446/?modelVersionId=None)
[CivitAI] LoCon SHA256: 7B8AD89A06760920306D945A68C0C2BD59D5A954D93ABF7292D042656509DBA7
